### ISSUE TITLE
device operations issues (wipe, reboot, hard lock)

### ISSUE THREAD

**Issue by waaalex** [wso2/cdmf-agent-android#110]
hello,

tested wso2 iot 3.1.0 and agent 3.1.21
in BYOD and COPE mode.

Factory reset (wipe), hard lock and reboot does not work.
tested with apk in debug and debugCope but no logs through adb logcat.

all other operations work.
thanks for help.

**Comment by rasika** [comment]
Hi waaalex,

Thank you very much for trying out WSO2 IoT Server 3.1.0. You can download the latest update through https://github.com/wso2/product-iots/releases/. As you mentioned Factory reset (wipe), hard lock and reboot won't work unless you install the WSO2 Android System Service App.  Please refer the docs at https://docs.wso2.com/display/IoTS310/Integrating+the+Android+System+Service+Application.

**Comment by waaalex** [comment]
This release have a ssl issue.
`[IoT-Core] ERROR - {org.apache.synapse.transport.passthru.SourceHandler} I/O error: Received fatal alert: certificate_unknown`

**Comment by waaalex** [comment]
In this update, there are many SSL errors.
hard to test.
In addition, i followed documentation (integrating admin service). just a thing that i'm not sure, for android.jar. i m not able to rebuild AOSP to get android.jar with hidden API.
I download android.jar from this address : https://github.com/anggrayudi/android-hidden-api

I will try to test this server release without SSL validation.

**Comment by rasika** [comment]
Hi waaalex, 

Can you elaborate more on the following statement; "In this update, there are many SSL and SAML errors.". Are you referring the server release or android agent release?

We would be very happy to help you on this; but we are unable to help you efficiently without information on the versions that you are using and steps you followed.

**Comment by waaalex** [comment]
Hi Rasika,

It's on server release.
When i configure WSO2 with my SSL certificates (with valid public certificate), i can't login on device manager (error 500 SAML exception, and key validation errors on wso2carbon.log file).
I also have tested enrolling Android in COPE mode with system service application (on latest server release) but it does not sync.

I made my tests quickly because i don't have so much time.
I will be able to remake installation from begining but i need time.
Can i write you in this thread later with logs?
thanks.

**Comment by waaalex** [comment]
i apologize, everything in SSL is here. i delete my post and yours and i will make tests with UPDATE6.
Thanks.
Regards.

**Comment by waaalex** [comment]
hello.
I remade tests.
I'm with a android 7.0 with agent 3.1.21 in COPE mode in WIFI (no SIM card).
enroll has issue, client loop at "enrolling device"
Device is detected by server but nothing more.
system service and agent are in debug mode but i can't logcat logs.
How can i get client logs?

Can you help me?
thanks.
Regards.
