### ISSUE TITLE
Auth failed against WSO2 EMM 2.2.0 server

### ISSUE THREAD

**Issue by herpiko** [wso2/cdmf-agent-android#14]
My goal is to use the EMM agent with GCM enabled (https://docs.wso2.com/display/EMM220/Configuring+WSO2+EMM+with+Firebase+Cloud+Messaging, with hidden API android.jar and so on).

I start from commit 9dce31483ccc5726 (v2.0.0 release). But the compiled APK failed to auth (401 returned). Then I inspecting the HTTP request and found that API_APPLICATION_CONTEXT in `utils/Constants` didn't same as the original APK that come from WSO2 EMM Download link. The right one is `dynamic-client-web`. 

After changing API_APPLICATION_CONTEXT to `dynamic-client-web`, the compiled APK still failed to auth with the server because of different payload content.

This is from original APK.
![screen shot 2017-02-06 at 2 23 44 pm](https://cloud.githubusercontent.com/assets/2534060/22637998/fba20f56-ec77-11e6-9ae9-cae2f2bca5b1.png)

And this is from the new compiled APK.
![screen shot 2017-02-06 at 2 23 55 pm](https://cloud.githubusercontent.com/assets/2534060/22638005/0bf132d8-ec78-11e6-85b8-787eefc888f3.png)

So, I thought the v2.0.0 tag has different commit with the original one. Which is the commit that matched with the released APK from download link in http://wso2.com/products/enterprise-mobility-manager/ ?

**Comment by charithag** [comment]
Hi,

For EMM220, you need to build agent from EMM repo[1]. This repo is containing agent for WSO2 IoTS.

Thanks.

[1] https://github.com/wso2/product-emm/tree/v2.2.0/modules/mobile-agents/android/client
