### ISSUE TITLE
If the user credentials are wrong, the "Authenticating" dialog never disapears

### ISSUE THREAD

**Issue by nemanjanedic** [wso2/cdmf-agent-android#18]
When trying to enroll a device with the IOTS 3.0.0, if a user does not enter correct credentials, the "Authenticating" dialog does not disappear. In the logs, there is a Volley error that the `/api-application-registration/register` returns `401`. This should be a normal case when the credentials are wrong but the app does not handle that correctly.

**Comment by charithag** [comment]
Fixed with commit https://github.com/wso2/cdmf-agent-android/pull/26/commits/3a39a9457830b35d999a792270bff03848ddf956
