### ISSUE TITLE
Migrate to Android Studio

### ISSUE THREAD

**Issue by Flinbor** [wso2/cdmf-agent-android#3]
Please migrate project from Eclipse to Android Studio
Migration done in my brunch:
https://github.com/Flinbor/emm-agent-android

**Comment by menasheu** [comment]
Migration really useful! Do you know where to find git code for the server side?

**Comment by Flinbor** [comment]
I do not work with it now.
I installed server side. After tests I find out that remote installing of
applications to android client doesn't work. Worked only wipe, messages and
lock.

**Comment by menasheu** [comment]
Anyway, I can try to manage with it. At least to understand the exchange of messages between the parties, so I either correct their code or develop mine. But I need something to start with. So if you know where to find theirs, I will be glad to receive it.
Thanks

**Comment by Flinbor** [comment]
https://github.com/wso2/product-emm

**Comment by wmfairuz** [comment]
@Flinbor so you are saying we cannot do a remote installing / updating with EMM? I thought this is the core feature of EMM (with the store, publisher and stuff)

**Comment by Flinbor** [comment]
it does not work for me,
tested on samsung note 3 (9005) android 5.0

On Thu, Jan 7, 2016 at 10:06 AM, Fairuz Wan Ismail <notifications@github.com

**Comment by wmfairuz** [comment]
@Flinbor Do I need to do something special for building the project? I posted the error above. Thanks

**Comment by Flinbor** [comment]
server side was builded by my admin, so I do not know how it is going,
for client side there is nothing special.

On Thu, Jan 7, 2016 at 10:25 AM, Fairuz Wan Ismail <notifications@github.com

**Comment by menasheu** [comment]
Remote installing of any Android app is not an EMM feature. You can put any apk anywhere and directly download and install. 
The installation of the client is really clean. 
For me the problem was the server side. Really cumbersome and I was not able to make the connection between the client and the server side at all. Tried with Ubuntu server with the link above. The client is calling pages that I could not find in the server project.

**Comment by wmfairuz** [comment]
@menasheu I'm not talking about any Android app. I'm talking about apps in the EMM store.

They did have this line in the WSO2 EMM feature list. 

Bulk push apps	Administrators can install a particular application to a specific user or a group of users via the EMM server.

**Comment by charithag** [comment]
Closing the issue as we have already migrated to Android Studio. If you have any other questions or queries regarding to different issue, please kindly create a new issue.

Thanks.
