### ISSUE TITLE
Shared UserID in IoT

### ISSUE THREAD

**Issue by MayukhaC** [wso2/cdmf-agent-android#46]
Hi, I have found that there is no

        android:sharedUserId="android.uid.system"
in IoT system-service application unlike wso2-emm system service application. Will it still be able to access the system permissionsn just by signing it with firmware key? 

Also app-catalog of the cdmf agent android applications doesnt have shareduserID with client. They cannot exchange information, can they? Why are the shareduserID's removed?

**Comment by kasundananjaya** [comment]
Hi, To answer your first question, yes it will be able to access services as the app will be built using the android.jar which has access to system level SDK. But if you sign it with firmware key, I advice you to have the above shared user ID as it's always better if that service can be working as a system app. (Unless you have it, your app won't be a system app anyway).

App catalog and CDMF agent does not need the same shared user ID as they communicate via IntentServices and those services are signature level + package identification level protected where the two apps can communicate ONLY if they are signed with the same certificate. So none of the external apps can not access these services. Alongside these IntentServices, there are Broadcasts with each app having broadcast receivers which will complete the communication and transaction followed.

**Comment by MayukhaC** [comment]
Hi, Thank you for the wonderful explanation.

so does the answer means that in order to do silent install of apps, all the three applications (system-service, client and app catalog) need to be signed by the same signatures and those signatures should be the device firmware signing key?

**Comment by kasundananjaya** [comment]
You're correct.
