### ISSUE TITLE
It is not working in Version 2.0.1

### ISSUE THREAD

**Issue by ghost** [wso2/cdmf-agent-android#5]
Emm agent android was working in version 1.1.0. We have updated the source to version 2.0.1. We are unable to login after updating the source code. Can you any please help me to solve this issue?

**Comment by kasundananjaya** [comment]
1.1.0 -> 2.0.1 has major platform level changes and 2.0.0+ is a total rewrite of the whole platform. You shouldn't use 2.0.0+ agent app with 1.1.0.

**Comment by vivekebics** [comment]
Hi Kasun Delgolla,
How do we need to proceed to solve this ? Is it possible to update the
source code ?

Regards,
Vivek E

**Comment by vivekebics** [comment]
I

**Comment by vivekebics** [comment]
How do we need to proceed to modify the source code ?

**Comment by charithag** [comment]
Closing the issue as per the @kasundananjaya 's comment
