### ISSUE TITLE
App compiled in "release" mode skips work profile creation

### ISSUE THREAD

**Issue by Whevw** [wso2/cdmf-agent-android#90]
**Description:**
When compiling the Android Agent as a “Release” build type the app starts the disclaimer activity and then skips the work profile creation activity to go straight to Enrollment activity during usage. This seems to be caused by a faulty else-if construction from what we’ve seen. There doesn’t seem to be an easy workaround without messing up some of the activity code. 

Are you aware of this issue or is it intended to not be able to create a work profile in release build?

**Suggested Labels:**
work profile, agent, build type

**Affected Product Version:**
3.1.21

**OS, DB, other environment details and versions:**    
3.1.0 IoT server

**Steps to reproduce:**
Build app as release build type
Install on phone
Try to enroll a phone and see it skips the work profile creation.

**Comment by charithag** [comment]
Release build variant is targeted for WSO2 Device could and the standalone build variant should use for configurable agent.
https://github.com/wso2/cdmf-agent-android/blob/master/client/client/build.gradle#L416
